import random

class TweetBuilder:

    person = [
        "Ace Ventura",
        "Ada McGrath",
        "Alex DeLarge",
        "Anton Chigurh",
        "Aragorn II Elessar",
        "Ash Williams",
        "Atticus Finch",
        "Austin Powers",
        "Axel Foley",
        "Beatrice Prior",
        "Beatrix Kiddo",
        "Wild Bill Hickok",
        "Boba Fett",
        "Brick Tamland",
        "Bruce Wayne",
        "Buffy Summers",
        "Bugs Bunny",
        "Buzz Lightyear",
        "Carreen O'Hara",
        "Charles Foster Kane",
        "Col. Christopher Brandon",
        "Clarice Starling",
        "Clark Kent",
        "Claudia",
        "Crystal Smith",
        "Daisy Adair",
        "Daisy Duck",
        "Daniel Plainview",
        "Lieutenant Danny Gilmartin",
        "Delores Herbig",
        "Donald Duck",
        "Donnie Darko",
        "Dory",
        "Count Dracula",
        "Edward Scissorhands",
        "Elisabeth of Austria",
        "Ellen Ripley",
        "Ellis Redding",
        "Emmett Brown",
        "Ethan Edwards",
        "Ethan Hunt",
        "Ferris Bueller",
        "Forrest Gump",
        "Frank Booth",
        "Frank Drebin",
        "Freddy Krueger",
        "Gandalf",
        "George Bailey",
        "George Lass",
        "Gollum",
        "Han Solo",
        "Hannibal Lecter",
        "Harry Burns",
        "Harry Callahan",
        "Harry Potter",
        "Indiana Jones",
        "Jack Skellington",
        "Jack Sparrow",
        "Jack Torrance",
        "James Bond",
        "Calamity Jane",
        "Jason Bourne",
        "Jeff Lebowski",
        "Jessica Rabbit",
        "John Connor",
        "John McClane",
        "Joy Lass",
        "Jules Winnfield",
        "Juno MacGuff",
        "Katie Brown",
        "Katniss Everdeen",
        "Keyser Soze",
        "Kyle Reese",
        "Lark Ingoldsby",
        "Princess Leia Organa",
        "Leon",
        "Luke Jackson",
        "Luke Skywalker",
        "Malcolm Reynolds",
        "Marge Gunderson",
        "Marlin",
        "Martin Blank",
        "Martin Riggs",
        "Marty McFly",
        "Marv",
        "Mary Poppins",
        "Mason",
        "Mathilda",
        "Max Rockatansky",
        "Maximus Decimus Meridius",
        "Michael Corleone",
        "Mickey Mouse",
        "Minnie Mouse",
        "Napoleon Dynamite",
        "Nemo",
        "Neo",
        "Norman Bates",
        "Patrick Bateman",
        "Peter Parker",
        "Peter Venkman",
        "Randal Graves",
        "R. P. McMurphy",
        "Reggie Lass",
        "Rhett Butler",
        "Rick Blaine",
        "Rocky Balboa",
        "Roger Rabbit",
        "Ron Burgundy",
        "Rosaleen",
        "Roxy Harvey",
        "Roy Batty",
        "Sally Albright",
        "Sarah Connor",
        "Scarlett OHara",
        "Agent Smith",
        "Snake Plissken",
        "Suellen OHara",
        "Tommy DeVito",
        "Tony Montana",
        "Tony Stark",
        "Travis Bickle",
        "Trinity",
        "Tyler Durden",
        "Darth Vader",
        "Vic Vega",
        "Vincenzo Coccotti",
        "Vito Corleone",
        "Walter Sobchak",
        "White Goodman",
        "Yoda"
        ]

    exclamation = [
        "ah",
        "a-ha",
        "ahem",
        "alas",
        "amen",
        "aw",
        "awesome",
        "bada bing",
        "bah",
        "baloney",
        "big deal",
        "bingo",
        "boo",
        "boohoo",
        "booya",
        "boy oh boy",
        "bravo",
        "brilliant",
        "brrr",
        "bye",
        "cheers",
        "come on",
        "cool",
        "cowabunga",
        "dang",
        "dear me",
        "duck",
        "duh",
        "eh",
        "enjoy",
        "excellent",
        "fabulous",
        "fantastic",
        "fiddledeedee",
        "finally",
        "fore",
        "gee whiz",
        "gee willikers",
        "giddyap",
        "goodbye",
        "gosh",
        "great",
        "great balls of fire",
        "ha",
        "heigh-ho",
        "hello",
        "help",
        "hey",
        "hi",
        "hip, hip, hooray",
        "ho ho ho",
        "ho-hum",
        "hooray",
        "howdy do",
        "huh",
        "ick",
        "kaboom",
        "kapow",
        "mama mia",
        "man",
        "marvelous",
        "my stars",
        "my word",
        "nah",
        "nope",
        "no problem",
        "no way",
        "nuts",
        "oh",
        "oh boy",
        "oh dear",
        "oh my",
        "oh my goodness",
        "oh my gosh",
        "oh no",
        "oh well",
        "OK",
        "ouch",
        "ow",
        "please",
        "shh",
        "super",
        "swell",
        "welcome",
        "well",
        "whoop-de-doo",
        "woo-hoo",
        "wow",
        "yabba dabba doo",
        "yadda, yadda, yadda",
        "yippee",
        "yummy"
        ]

    name = [
        "Alex",
        "Anthony",
        "Barbara",
        "Betty",
        "Brian",
        "Burton",
        "Carol",
        "Charles",
        "Christopher",
        "Daniel",
        "David",
        "Deborah",
        "Donald",
        "Donna",
        "Dorothy",
        "Edward",
        "Elizabeth",
        "George",
        "Helen",
        "James",
        "Jason",
        "Jeff",
        "Jennifer",
        "John",
        "Joseph",
        "Karen",
        "Kenneth",
        "Kevin",
        "Kimberly",
        "Laura",
        "Linda",
        "Lisa",
        "Margaret",
        "Maria",
        "Mark",
        "Mary",
        "Michael",
        "Michelle",
        "Nancy",
        "Patricia",
        "Paul",
        "Richard",
        "Robert",
        "Ronald",
        "Ruth",
        "Sandra",
        "Sarah",
        "Sharon",
        "Stefan",
        "Steven",
        "Susan",
        "Thomas",
        "Vivek",
        "William"
        ]

    def generate(self, colour):
        retval = random.choice(self.name)
        retval += " would like " + colour
        retval += " for " + random.choice(self.person)
        retval += ", " + random.choice(self.exclamation) + "!"
        return retval
